feature(migration): migration script
catenax-ng/tx-portal-assets pull request #137
Opened 2023-03-29 08:19 UTC by jjeroch

2023-04-04 09:06 UTC, oyo approved these changes

2023-04-11 14:38 UTC, evegufy commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +Migration script existing, based on the service type which is fetched for all existing data from portal table service_assigned_service_types, the technical_user_needed attribute is set to "true" for
@jjeroch to which migration script do you refer here? The 'normal' migration job or a separate script?

2023-04-11 14:39 UTC, evegufy requested changes

2023-04-12 06:57 UTC, jjeroch commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +?? Existing company registration data currently under validation are automatically expanded with the respective attribute values for the new tables/attributes ??
that is getting removed before merging
Reason: That section got highlighted with "??" since statement needed special check by backend team

2023-04-12 06:58 UTC, jjeroch commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +Migration script existing, based on the service type which is fetched for all existing data from portal table service_assigned_service_types, the technical_user_needed attribute is set to "true" for
@Phil91 can you have a look at Evelyn's question please

2023-04-17 08:28 UTC, ntruchsess requested changes

2023-04-17 08:28 UTC, ntruchsess commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +* NEW: table "media_types"
this is actually a 1.2.0 feature

2023-04-17 08:28 UTC, ntruchsess commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +* NEW: portal.processes
this is actually a 1.1.0 feature (defined in migration https://github.com/catenax-ng/tx-portal-backend/blob/c14828e39828af663dfe6e6c6d710699d9173ea7/src/portalbackend/PortalBackend.Migrations/Migrations/20230309082649_1.1.0.cs#L114 )

2023-04-17 08:28 UTC, ntruchsess commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +Migration script existing, based on the service type which is fetched for all existing data from portal table service_assigned_service_types, the technical_user_needed attribute is set to "true" for
'migration script' refers to the term 'migrations' as it is defined by the ef-core framework: https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations

2023-04-17 08:54 UTC, jjeroch commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +* NEW: portal.processes
(y)

2023-04-17 09:09 UTC, jjeroch commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +* NEW: portal.processes
@ntruchsess  info added, however I found a couple of additional document types - I guess some of them have been released later then 1.1.0 - could you do a quick recheck please

2023-04-17 09:23 UTC, ntruchsess commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +* NEW: portal.processes
document_types are not directly linked to media_types. A document_type describes what the document is being used for while a media_type describes what the file-format is.
If you mean 'media_types' then yes, there are a few more (PEM, CA_CERT, PKX_CER, OCTET), but those should not exist in any pre-1.2.0 database. From my understanding there is no pre-1.2.0 code that would create such.

2023-04-17 09:26 UTC, jjeroch commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +* NEW: portal.processes
ok, I kick them out again and keep the list to the initial created types.
And yes, I meant media type ;)

2023-04-17 22:18 UTC, ntruchsess requested changes

2023-04-17 22:18 UTC, ntruchsess commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +Migration script existing, based on the service type which is fetched for all existing data from portal table service_assigned_service_types, the technical_user_needed attribute is set to "true" for
Line 81 and 84 are duplicates

2023-05-02 14:17 UTC, merged