enhance(intro):introduction and images
catenax-ng/tx-portal-assets pull request #156
Opened 2023-04-10 19:57 UTC by jjeroch

2023-04-11 03:21 UTC, oyo requested changes
please try to reduce the image size as this will result in unnecessary much network traffic and bad user experience due to long loading times.

2023-04-11 03:21 UTC, oyo commented on public/assets/images/content/CXMarketplace_Teaser.png
This image file with 4.3 MB is way too large to send over the network regularly especially as it doesn't seem to contain a lot of valuable information. These kind of images are perfectly suited for svg file format. In case it has been created with Powerpoint there is a way to export images as .svg:
https://office-watch.com/2022/save-image-slides-svg-format/

This file as an svg would result in a file size about 1/100th of the 4.3 MB bitmap here. If for some reason it must be a bitmap format I suggest to:
a) reduce the size to about 800px width and
b) save it as either .jpg with max 90% quality or indexed .png
doing this will bring the file size down to about 100 kB (1/43th) with only slight quality losses. As an example I attach examples here:

.jpg, 800px, 90%, 104 kB
![CXMarketplace_Teaser-800-90](https://user-images.githubusercontent.com/351487/231046958-126700b3-ff9e-4618-8280-dc955c943147.jpg)

.png, 800px, indexed 64 colors, 92 kB
![CXMarketplace_Teaser-800-idx](https://user-images.githubusercontent.com/351487/231047072-287fe5b6-e7b7-49a7-a16e-05b18cd031fb.png)

2023-04-11 08:44 UTC, oyo commented on public/assets/images/content/CXMarketplace_Teaser.png
okay, for now updated your PR with a 4kB SVG file - will write a documentation page about how to deal with images.

2023-04-11 11:08 UTC, jjeroch commented
images updated to svg; just kept the placeholder with png since svg was even huger

2023-04-12 06:45 UTC, oyo approved these changes
updated your pr and reduced the image file size of all three pics

2023-04-12 06:55 UTC, merged