Feature docu/service release approval
catenax-ng/tx-portal-assets pull request #178
Opened 2023-05-02 08:53 UTC by jjeroch

2023-05-11 06:38 UTC, oyo requested changes
references images from user account

2023-05-11 06:38 UTC, oyo commented on developer/05. Service(s)/03. Service Release Approval/01. Service Approval Board Overview.md
> +<img width="318" alt="image" src="https://user-images.githubusercontent.com/94133633/213944346-28d2a92d-9341-4761-a815-39a99d07b514.png">
we must stop adding images from user accounts. This is not sustainable - when the user account is deleted the documentation doesn't work any more. Instead upload the image to the assets and set the link here (can also be the github link)

2023-05-15 06:26 UTC, jjeroch commented on developer/05. Service(s)/03. Service Release Approval/01. Service Approval Board Overview.md
> +<img width="318" alt="image" src="https://user-images.githubusercontent.com/94133633/213944346-28d2a92d-9341-4761-a815-39a99d07b514.png">
hi martin, since we have done this now already in several places I would not stop one pr - this is a general cleanup task but shouldnt block the documentation

2023-05-15 06:45 UTC, oyo approved these changes

2023-05-15 06:46 UTC, oyo commented on developer/05. Service(s)/03. Service Release Approval/01. Service Approval Board Overview.md
> +<img width="318" alt="image" src="https://user-images.githubusercontent.com/94133633/213944346-28d2a92d-9341-4761-a815-39a99d07b514.png">
okay - approved now

2023-05-15 11:28 UTC, merged