Create Auditing.md
catenax-ng/tx-portal-assets pull request #6
Opened 2022-12-27 09:14 UTC by jjeroch

2023-01-02 04:39 UTC, oyo requested changes
see one question about some code formatting

2023-01-02 04:39 UTC, oyo commented on docs/Technical Details/Auditing.md
> +       x.ToTable("audit_company_users_cplp_1254_db_audit");       });`
this code block looks weird - shouldn't we put each of the `x.Ignore(...)` statements into a separate line?

2023-01-03 00:34 UTC, jjeroch commented on docs/Technical Details/Auditing.md
> +       x.ToTable("audit_company_users_cplp_1254_db_audit");       });`
done

2023-01-04 08:07 UTC, oyo approved these changes

2023-01-04 08:14 UTC, merged