Added new content folder for static template images
catenax-ng/tx-portal-assets pull request #98
Opened 2023-02-28 06:33 UTC by manojava-gk

2023-02-28 12:36 UTC, jjeroch requested changes
a couple of images are still to be added (the once which are located in the page "company roles"

2023-03-01 21:32 UTC, jjeroch commented
@manojava-gk  do we have a related pr on frontend side to ensure that images are correctly fetched?

2023-03-02 05:50 UTC, manojava-gk commented
> @manojava-gk do we have a related pr on frontend side to ensure that images are correctly fetched?

Front end side yes. here is the link - https://github.com/catenax-ng/tx-portal-frontend/pull/228

2023-03-02 14:01 UTC, oyo approved these changes
I don't approve that `imageUrl` path prefix. Prefer convention over configuration. Also a url path starting with `/images/content/` doesn't exist

2023-03-02 15:38 UTC, manojava-gk commented on public/assets/content/de/companyroles.json
> +        "imageUrl": "/images/content//images/content/teaser.png",
Initially I was expecting http url. For that reason it is named as imageUrl. But it is no more http url. It is just a path. I can update the attribute name here

2023-03-06 06:11 UTC, manojava-gk commented
Shall I merge this PR? @oyo

2023-03-06 08:57 UTC, oyo approved these changes

2023-03-06 11:17 UTC, merged